### PR TITLE
Support for Level 9 Raids + correct names for Ultrabeasts

### PR DESCRIPTION
**Pull request by zastel1983**
Support for Level 9 Raids + correct  names for ultrabeast-raids

### CODE REVIEW

**Comment by focusbbs** [comment]
Changes create errorlog an crash:

2022-10-16T14:06:03: SyntaxError: cannot assign to literal
2022-10-16T14:06:03: Traceback (most recent call last):
2022-10-16T14:06:03:   File "raid-main.py", line 5, in <module>
2022-10-16T14:06:03:     import createMessage
2022-10-16T14:06:03:   File "/home/pokemon/MAD/addons/raid_bot/createMessage.py", line 25
2022-10-16T14:06:03:     19 = ""
2022-10-16T14:06:03:     ^

**Comment by zastel1983** [comment]
Everything fine here. Did you edit the file manually?

**Comment by zastel1983** [comment]
Ah I see. You entered 19 instead of l9. It’s a small L

**Comment by focusbbs** [comment]
Uh, what a mistake, iam sorry. You are right :-)

**Pull request closed without merging**
